/* Generated from godot/shaders/atmosphere.gdshader. */
static const char *sky_fragment =
"#version 300 es\n"
"precision highp float;\n"
"precision highp int;\n"
"in vec2 v_uv;\n"
"out vec4 result;\n"
"#define UV vec2(v_uv.x, 1.0-v_uv.y)\n"
"#define COLOR result\n"
"uniform float scene_time;\n"
"uniform float sun_elevation;\n"
"uniform float sun_azimuth;\n"
"uniform float cloud_cover;\n"
"uniform float fog_density;\n"
"// Integrated on the CPU so a wind change cannot reposition the cloud field.\n"
"uniform float cloud_offset;\n"
"uniform float lightning;\n"
"uniform bool reduced_motion;\n"
"uniform float aspect_ratio;\n"
"// Weather tone is independent of animation and particle visibility. Cloud\n"
"// cover controls density; dry clouds alone must not imply a rain storm.\n"
"uniform float weather_dim;\n"
"\n"
"// Value noise uses arithmetic hashes, avoiding trigonometry in the cloud loops.\n"
"// Hash without Sine: Copyright (c) 2014 David Hoskins, MIT license.\n"
"// https://www.shadertoy.com/view/4djSRW \u2014 see THIRD_PARTY_NOTICES.md.\n"
"float hash21(vec2 p) {\n"
"    vec3 q = fract(vec3(p.x, p.y, p.x) * 0.1031);\n"
"    q += dot(q, q.yzx + 33.33);\n"
"    return fract((q.x + q.y) * q.z);\n"
"}\n"
"\n"
"float noise2(vec2 p) {\n"
"    vec2 i = floor(p);\n"
"    vec2 f = fract(p);\n"
"    f = f * f * (3.0 - 2.0 * f);\n"
"    return mix(mix(hash21(i), hash21(i + vec2(1.0, 0.0)), f.x),\n"
"               mix(hash21(i + vec2(0.0, 1.0)), hash21(i + vec2(1.0)), f.x), f.y);\n"
"}\n"
"\n"
"float cloud_noise(vec2 p) {\n"
"    float result = 0.0;\n"
"    float weight = 0.5;\n"
"    // Six fixed octaves preserve small billows in the half-resolution buffer.\n"
"    // Still fixed work per pixel, without ray marching or dependent loops.\n"
"    for (int i = 0; i < 6; i++) {\n"
"        result += noise2(p) * weight;\n"
"        p = mat2(vec2(1.60, 1.20), vec2(-1.20, 1.60)) * p + vec2(7.1, 13.7);\n"
"        weight *= 0.5;\n"
"    }\n"
"    return result / 0.984375;\n"
"}\n"
"\n"
"float light_noise(vec2 p) {\n"
"    return noise2(p) * 0.6667 + noise2(p * 2.0 + vec2(11.3, 8.7)) * 0.3333;\n"
"}\n"
"\n"
"vec4 cloud_layer(vec2 p, vec2 light_direction, float cover, float daylight,\n"
"                 float dusk, float flash, float layer_strength) {\n"
"    // Broad warped shapes plus directional density differences suggest lit\n"
"    // billows. Light changes independently of alpha, rather than tinting noise.\n"
"    vec2 warp = vec2(noise2(p * 0.55 + vec2(19.2, 4.7)),\n"
"                     noise2(p * 0.55 + vec2(3.5, 27.1))) - vec2(0.5);\n"
"    p += warp * 0.65;\n"
"    float body = cloud_noise(p);\n"
"    float threshold = mix(1.02, 0.32, cover);\n"
"    float density = smoothstep(threshold - 0.08, threshold + 0.10, body);\n"
"    float light_side = light_noise(p + light_direction * 0.22);\n"
"    // Fine density variation provides restrained relief within overcast areas,\n"
"    // rather than flattening the entire cloud mass into a blurred color field.\n"
"    float detail = noise2(p * 8.0 + vec2(31.7, 5.9)) - 0.5;\n"
"    float relief = clamp(0.50 + (body - light_side) * 3.1 + detail * 0.15, 0.0, 1.0);\n"
"    float rim = pow(1.0 - density, 2.0) * relief;\n"
"    float overcast = smoothstep(0.72, 1.0, cover);\n"
"    float weather = clamp(weather_dim, 0.0, 1.0);\n"
"    // Diffuse daylight keeps dry cloud undersides silver, even at full cover.\n"
"    // Reserve the old deep slate shadows for actual wet/storm conditions.\n"
"    vec3 day_shadow = mix(vec3(0.65, 0.74, 0.83), vec3(0.60, 0.69, 0.77), overcast);\n"
"    vec3 day_lit = mix(vec3(0.97, 0.99, 1.0), vec3(0.90, 0.94, 0.97), overcast);\n"
"    day_shadow = mix(day_shadow, mix(vec3(0.35, 0.43, 0.53), vec3(0.15, 0.20, 0.28), overcast), weather);\n"
"    day_lit = mix(day_lit, mix(vec3(0.88, 0.93, 0.96), vec3(0.64, 0.70, 0.77), overcast), weather);\n"
"    vec3 shadow = mix(vec3(0.035, 0.050, 0.095), day_shadow, daylight);\n"
"    vec3 lit = mix(vec3(0.15, 0.20, 0.30), day_lit, daylight);\n"
"    lit = mix(lit, vec3(0.99, 0.69, 0.49), dusk * 0.52);\n"
"    vec3 color = mix(shadow, lit, relief * 0.62 + rim * 0.28);\n"
"    color += vec3(0.58, 0.66, 0.90) * flash * (0.35 + body * 0.65);\n"
"    float alpha = density * layer_strength * smoothstep(0.015, 0.12, cover);\n"
"    return vec4(color, alpha);\n"
"}\n"
"\n"
"void main() {\n"
"    vec2 uv = UV;\n"
"    float aspect = max(aspect_ratio, 0.1);\n"
"    float elevation = clamp(sun_elevation, -90.0, 90.0);\n"
"    float daylight = smoothstep(-8.0, 12.0, elevation);\n"
"    float night = 1.0 - smoothstep(-12.0, -2.0, elevation);\n"
"    float dusk = exp(-pow((elevation + 1.0) / 9.0, 2.0));\n"
"    float cover = clamp(cloud_cover, 0.0, 1.0);\n"
"    float fog = clamp(fog_density, 0.0, 1.0);\n"
"    // Global extinction prevents the artistic moon/stars from punching through\n"
"    // thick overcast or fog; local cloud alpha still masks partial-cloud gaps.\n"
"    // Clear-night visibility stays1.0. Two scalar ramps add no noise samples.\n"
"    float celestial_visibility = (1.0 - smoothstep(0.35, 0.80, cover))\n"
"                               * (1.0 - smoothstep(0.20, 0.80, fog));\n"
"    float night_visibility = night * celestial_visibility;\n"
"    float flash = clamp(lightning, 0.0, 1.0);\n"
"    float time = scene_time;\n"
"\n"
"    float overcast = smoothstep(0.72, 1.0, cover);\n"
"    float weather = clamp(weather_dim, 0.0, 1.0);\n"
"    vec3 day_zenith = mix(vec3(0.18, 0.48, 0.78), vec3(0.38, 0.57, 0.75), overcast);\n"
"    vec3 day_horizon = mix(vec3(0.66, 0.82, 0.91), vec3(0.71, 0.81, 0.88), overcast);\n"
"    day_zenith = mix(day_zenith, mix(vec3(0.16, 0.39, 0.65), vec3(0.22, 0.28, 0.36), overcast), weather);\n"
"    day_horizon = mix(day_horizon, mix(vec3(0.66, 0.80, 0.86), vec3(0.44, 0.50, 0.56), overcast), weather);\n"
"    vec3 zenith = mix(vec3(0.014, 0.022, 0.058), day_zenith, daylight);\n"
"    vec3 horizon = mix(vec3(0.065, 0.083, 0.14), day_horizon, daylight);\n"
"    zenith = mix(zenith, vec3(0.14, 0.13, 0.29), dusk * 0.48);\n"
"    horizon = mix(horizon, vec3(0.83, 0.47, 0.36), dusk * 0.76);\n"
"    float vertical = pow(clamp(uv.y, 0.0, 1.0), 1.45);\n"
"    vec3 sky = mix(zenith, horizon, vertical);\n"
"    float haze = exp(-max(0.88 - uv.y, 0.0) * 9.0);\n"
"    sky += mix(vec3(0.023, 0.028, 0.042), vec3(0.09, 0.10, 0.08), daylight) * haze;\n"
"\n"
"    vec2 sun_position = vec2(0.5 + sin(radians(sun_azimuth - 180.0)) * 0.43,\n"
"                             0.88 - sin(radians(elevation)) * 0.92);\n"
"    float sun_distance = length((uv - sun_position) * vec2(aspect, 1.0));\n"
"    float sun_visible = smoothstep(-3.0, 1.0, elevation) * (1.0 - smoothstep(0.72, 0.98, cover));\n"
"    sun_visible *= 1.0 - smoothstep(0.25, 0.95, fog);\n"
"    vec3 sunlight = mix(vec3(1.0, 0.47, 0.22), vec3(1.0, 0.91, 0.70), smoothstep(0.0, 25.0, elevation));\n"
"    sky += sunlight * exp(-sun_distance * 8.5) * 0.18 * sun_visible;\n"
"    sky += sunlight * exp(-sun_distance * sun_distance * 180.0) * 0.24 * sun_visible;\n"
"    float disk = 1.0 - smoothstep(0.018, 0.022, sun_distance);\n"
"    sky = mix(sky, vec3(1.0, 0.97, 0.87), disk * sun_visible);\n"
"\n"
"    // Sparse, subpixel-friendly stars. Slow twinkle freezes in reduced motion.\n"
"    vec2 star_grid = uv * vec2(aspect, 1.0) * 85.0;\n"
"    vec2 cell = floor(star_grid);\n"
"    float star_seed = hash21(cell + vec2(61.7, 3.8));\n"
"    vec2 star_position = vec2(hash21(cell + vec2(7.4, 91.2)), hash21(cell + vec2(42.1, 5.3)));\n"
"    float star_distance = length(fract(star_grid) - star_position);\n"
"    float star = (1.0 - smoothstep(0.025, 0.105, star_distance)) * step(0.981, star_seed);\n"
"    float twinkle = reduced_motion ? 0.85 : 0.85 + 0.15 * sin(time * 0.35 + star_seed * 67.0);\n"
"    sky += vec3(0.65, 0.74, 0.92) * star * twinkle * night_visibility * (1.0 - vertical);\n"
"\n"
"    // An artistic crescent, not an astronomical lunar phase calculation.\n"
"    vec2 moon_position = vec2(clamp(1.0 - sun_position.x, 0.18, 0.82), 0.22);\n"
"    vec2 moon_uv = (uv - moon_position) * vec2(aspect, 1.0);\n"
"    float moon_distance = length(moon_uv);\n"
"    float moon_disk = 1.0 - smoothstep(0.021, 0.024, moon_distance);\n"
"    float moon_cut = smoothstep(0.021, 0.024, length(moon_uv - vec2(0.010, -0.003)));\n"
"    sky += vec3(0.19, 0.25, 0.39) * exp(-moon_distance * 30.0) * night_visibility;\n"
"    sky = mix(sky, vec3(0.79, 0.84, 0.92), moon_disk * moon_cut * night_visibility);\n"
"\n"
"    vec2 sky_point = uv * vec2(aspect, 1.0);\n"
"    float drift = cloud_offset;\n"
"    // Distant sunlight has a constant direction across the cloud field. A\n"
"    // per-pixel direction to the sun disk creates an artificial radial cusp.\n"
"    vec2 light_direction = normalize(vec2(sin(radians(sun_azimuth - 180.0)) * 0.7,\n"
"                                         -0.5 - max(sin(radians(elevation)), 0.0) * 0.4));\n"
"    vec4 high_clouds = cloud_layer(sky_point * vec2(2.7, 4.1) + vec2(-drift * 0.65, 6.7),\n"
"                                   light_direction, cover * 0.88, daylight, dusk, flash, 0.60);\n"
"    vec4 low_clouds = cloud_layer(sky_point * vec2(3.8, 5.2) + vec2(-drift, 21.3),\n"
"                                  light_direction, cover, daylight, dusk, flash, 0.87);\n"
"    float cloud_horizon = 1.0 - smoothstep(0.77, 1.0, uv.y);\n"
"    sky = mix(sky, high_clouds.rgb, high_clouds.a * cloud_horizon);\n"
"    sky = mix(sky, low_clouds.rgb, low_clouds.a * cloud_horizon);\n"
"\n"
"    vec3 fog_color = mix(vec3(0.12, 0.15, 0.21), vec3(0.72, 0.78, 0.80), daylight);\n"
"    fog_color = mix(fog_color, vec3(0.77, 0.58, 0.51), dusk * 0.38);\n"
"    // Fog veils the whole sky, with stronger extinction toward the horizon.\n"
"    // A horizon-only treatment looked like a clear day above a pale lower edge.\n"
"    float fog_alpha = fog * (0.48 + 0.50 * smoothstep(0.0, 1.0, uv.y));\n"
"    sky = mix(sky, fog_color, fog_alpha);\n"
"    COLOR = vec4(clamp(sky, vec3(0.0), vec3(1.0)), 1.0);\n"
"}\n";
