package updater

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/joega/a-weather-app/internal/safeio"
)

func launcherContents(template []byte, executable, icon string) []byte {
	lines := []string{}
	for _, line := range strings.Split(strings.TrimSuffix(string(template), "\n"), "\n") {
		if strings.HasPrefix(line, "TryExec=") {
			continue
		}
		if strings.HasPrefix(line, "Exec=") {
			line = "Exec=\"" + executable + "\""
		}
		if strings.HasPrefix(line, "Icon=") {
			line = "Icon=" + icon
		}
		lines = append(lines, line)
	}
	return []byte(strings.Join(lines, "\n") + "\n")
}

// migrateLauncher changes only an exact launcher generated by our old app.
// Custom launchers and unrelated commands are preserved byte-for-byte.
func (l *LinuxInstallation) migrateLauncher(t Transaction) error {
	base := filepath.Dir(l.DataRoot)
	apps := filepath.Join(base, "applications")
	file := filepath.Join(apps, "a-weather-app.desktop")
	info, e := os.Lstat(file)
	if errors.Is(e, os.ErrNotExist) {
		return nil
	}
	if e != nil {
		return e
	}
	st, ok := info.Sys().(*syscall.Stat_t)
	if !ok || !info.Mode().IsRegular() || st.Uid != uint32(os.Geteuid()) || st.Nlink != 1 || info.Mode().Perm()&0022 != 0 || info.Size() > 8192 {
		return nil
	}
	if e = ownedDirectory(apps); e != nil {
		return e
	}
	raw, e := safeio.ReadFile(file, 8192)
	if e != nil {
		return e
	}
	template, e := safeio.ReadFile(filepath.Join(t.OldRuntime, "packaging/a-weather-app.desktop"), 8192)
	if e != nil {
		return e
	}
	icon := filepath.Join(base, "icons/hicolor/scalable/apps/a-weather-app.svg")
	expected := launcherContents(template, filepath.Join(t.OldRuntime, "a-weather-app"), icon)
	if !bytes.Equal(raw, expected) {
		return nil
	}
	next := launcherContents(template, filepath.Join(l.DataRoot, "current/a-weather-app"), icon)
	for _, r := range base + l.DataRoot {
		if r < 32 || r == 127 || strings.ContainsRune("\\\"`$%=", r) {
			return errors.New("unsupported launcher path")
		}
	}
	tmp, e := os.MkdirTemp(apps, ".weather-launcher-")
	if e != nil {
		return e
	}
	defer os.RemoveAll(tmp)
	staged := filepath.Join(tmp, "launcher")
	if e = os.WriteFile(staged, next, info.Mode().Perm()); e != nil {
		return e
	}
	out, e := os.OpenFile(staged, os.O_RDWR, 0)
	if e != nil {
		return e
	}
	e = out.Sync()
	out.Close()
	if e != nil {
		return e
	}
	current, e := os.Lstat(file)
	if e != nil || !os.SameFile(info, current) {
		return errors.New("launcher changed during update")
	}
	currentRaw, e := safeio.ReadFile(file, 8192)
	if e != nil || !bytes.Equal(currentRaw, expected) {
		return errors.New("launcher was edited during update")
	}
	if e = os.Rename(staged, file); e != nil {
		return e
	}
	d, e := os.Open(apps)
	if e != nil {
		return e
	}
	defer d.Close()
	return d.Sync()
}
